name: hexlet-lint

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Run linter and pytest
        run: |
          make lint